default: &default
  secret_key_base: <%= ENV["SECRET_BASE_KEY"] %>
  json_placeholder: <%= ENV["JSON_PLACEHOLDER_TOKEN"] %>

development:
  <<: *default

test:
  <<: *default  

staging:
  <<: *default

production:
  <<: *default